### ISSUE TITLE
README improvement - explain what this actually does

### ISSUE THREAD

**Issue by hangtwenty** [ajk8/fencepy#3]
I get the intention, but how does it do it? More importantly, how is this different from `virtualenvwrapper`?

**Comment by ajk8** [comment]
Having looked at `virtualenvwrapper`, I think there is definitely some overlap there.  I think `fencepy` fills a different niche, though.  `virtualenvwrapper` is a more mature, feature-rich tool, for sure, but it has a signifiicantly broader scope.

One of the first things I noticed when trying it out is that it passes arguments directly to `virtualenv` (wrapper, go figure), which includes the name of the virtual environment.   One key tenet of `fencepy` is that it completely abstracts away naming, location, and all (for now) options from `virtualenv`.  While this may seem limiting, it encourages frequent setup and teardown of virtual environments, which in turns leads to robust reproducibility.  I think the simplicity is a benefit.

Another key difference is that, since `fencepy` is written in pure python, including the CLI entry points, it can function in any environment, limited only by `virtualenv`'s activate scripts.  `virtualenvwrapper` has its entrypoint written in shell, which confers distinct advantages, but also carries the disadvantage of being compatible only with the shells listed (bash, ksh, zsh).  I am currently working in fish shell, so that's a dealbreaker for me.

As far as how it works, I will add some information to the readme.

**Comment by hangtwenty** [comment]
Hmm. Why not assume the system has `bash` (most do) and just make calls to `bash` directly and not care what the primary shell is? If you used this approach, it is possible that this repository could be under a hundred lines of (non-boilerplate) code.

**Comment by ajk8** [comment]
I appreciate the rigor.  Having spent a little time thinking about it, though, I'm not sure wrapping `virtualenvwrapper` would buy much.  For instance, while I could build an environment, I don't think I'd be able to activate it in `fish` without a rewrite.  Also, I wouldn't want to handle json in `bash` (for configuring sublime linter).  Besides, as of now, the only "wrapped" functionality is the functionality of `virtualenv` itself.  If you'd like to discuss it further, feel free to email me directly.
